### ISSUE TITLE
Support ConfigMap to externalize the environment variable in Kubernetes Exporter Project

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/devstudio-tooling-ei#1306]
**Description:**
The current implementation added key-value pair directly into the integration_cr.yaml file. It is good practice to maintain Kubernetes objects and data separately. 

integration_cr.yaml
```
---
apiVersion: "integration.wso2.com/v1alpha1"
kind: "Integration"
metadata:
  name: "MySample"
spec:
  replicas: 1
  image: "indikasampath2000/sample:v1"
  env:
  - name: "endpoint1"
    value: "http://localhost:8080/"
```

Let's introduce the following approach instead of the above.

integration_cr.yaml
```
---
apiVersion: "integration.wso2.com/v1alpha1"
kind: "Integration"
metadata:
  name: "MySample"
spec:
  replicas: 1
  image: "indikasampath2000/sample:v1"
  env:
  - name: ENDPOINT1
    valueFrom:
      configMapKeyRef:
        name: MySample-Data
        key: endpoint1
```

data.yaml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: MySample-Data
data:
  endpoint1: "http://localhost:8080/"
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
We can use the following syntax to create environment variables from all keys in ConfigMap inside the deployment.toml 

```yaml
spec:
  containers:
    - name: cm-container-3
      .....
      envFrom:
         - configMapRef:
             name: CONFIG_MAP_NAME
```
